name: ben1212docker

trigger:
- main
#- feature/*

pool: Docker

# variables:
#   - group: "Staging Variables"

# Continuous Integration Process

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- task: CopyFiles@2
  displayName: 'Copy Files to: /home/ubuntu/repo'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/**'
    TargetFolder: /home/ubuntu/repo

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: ben1212docker.azurecr.io
    repository: 'weight-app-repo'
    Dockerfile: /home/ubuntu/repo/Dockerfile



# Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: "dockhost000001"
#       resourceType: VirtualMachine

#     strategy:
#       runOnce:
#         deploy:
#           steps:
          

# Continuous Delivery Process for Production Environment


# - stage: DeployToProduction
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#       - deployment: production
#         displayName: Deploy to Production
#         environment:
#           name: <<YOUR ENVIRONMENT NAME>>
#           resourceType: VirtualMachine
#         strategy:
#           runOnce:
#             deploy:
#               steps:
              
