name: ben1212docker

trigger:
- main
#- feature/*

pool: Docker
  #vmImage: ubuntu-latest


# variables:
#   - group: "Staging Variables"

# Continuous Integration Process

steps:
- task: ChocolateyToolInstaller@0
  inputs:
    force: true

- task: CmdLine@2
  inputs:
    script: 'choco install docker-desktop'

- task: Docker@2
  inputs:
    containerRegistry: 'ben1212docker.azurecr.io'
    repository: 'weight-app-repo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


# Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: "dockhost000001"
#       resourceType: VirtualMachine

#     strategy:
#       runOnce:
#         deploy:
#           steps:
          

# Continuous Delivery Process for Production Environment


# - stage: DeployToProduction
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#       - deployment: production
#         displayName: Deploy to Production
#         environment:
#           name: <<YOUR ENVIRONMENT NAME>>
#           resourceType: VirtualMachine
#         strategy:
#           runOnce:
#             deploy:
#               steps:
              
