# pipeline

name: Week08-Docker

trigger:
- main
- feature

pool: Docker

variables:
  containerSrvReg: weight-app-repo
  imageRepository: weightapprepo
  containerRegLogin: ben1213test.azurecr.io

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerSrvReg)
          repository: 'weightapprepo'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  variables: 
    - group: "staging-vars"
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: staging
    displayName: Deploy to Staging
    environment:
      name: staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - template: templates/pipeline-cd-template.yml

# Continuous Delivery Process for Production Environment
- stage: DeployToProduction
  variables: 
    - group: "production-vars"
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: production
    displayName: Deploy to Production
    environment:
      name: production
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - template: templates/pipeline-cd-template.yml
